#!/bin/bash
# GitHub CodeQL Security Report Generator (Bash version)
# Uses curl and jq for better compatibility

set -e

echo "🚀 Starting CodeQL Report Generation..."

REPO=$GITHUB_REPOSITORY
TOKEN=$GITHUB_TOKEN
API_URL="https://api.github.com/repos/${REPO}/code-scanning/alerts"

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Installing jq..."
    sudo apt-get update -qq
    sudo apt-get install -y jq > /dev/null 2>&1
fi

echo "📡 Fetching CodeQL alerts..."

# Fetch alerts
ALERTS=$(curl -s \
  -H "Authorization: token ${TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "${API_URL}?per_page=100&state=open")

TOTAL=$(echo "$ALERTS" | jq 'length')
ERRORS=$(echo "$ALERTS" | jq '[.[] | select(.rule.severity == "error")] | length')
WARNINGS=$(echo "$ALERTS" | jq '[.[] | select(.rule.severity == "warning")] | length')
NOTES=$(echo "$ALERTS" | jq '[.[] | select(.rule.severity == "note")] | length')

echo "✓ Fetched ${TOTAL} CodeQL alerts"
echo "  - Errors: ${ERRORS}"
echo "  - Warnings: ${WARNINGS}"
echo "  - Notes: ${NOTES}"

# Generate Markdown Report
cat > security-report.md << 'EOF'
# 🔒 CodeQL Security Report

EOF

echo "" >> security-report.md
echo "**Generated:** $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)" >> security-report.md
echo "**Repository:** ${REPO}" >> security-report.md
echo "" >> security-report.md

cat >> security-report.md << EOF

## Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | ${ERRORS} |
| 🟡 Warning | ${WARNINGS} |
| 🔵 Note | ${NOTES} |
| **TOTAL** | **${TOTAL}** |

EOF

if [ "$TOTAL" -eq 0 ]; then
    cat >> security-report.md << 'EOF'

## ✓ Status

✅ No security issues detected! Your code passed all CodeQL security checks.

EOF
else
    echo "" >> security-report.md
    echo "## 🔴 Critical Issues (${ERRORS})" >> security-report.md
    echo "" >> security-report.md
    echo "$ALERTS" | jq -r '.[] | select(.rule.severity == "error") | "### \(.rule.name)\n- **Rule:** `\(.rule.id)`\n- **File:** `\(.most_recent_instance.location.path)` (Line \(.most_recent_instance.location.start_line))\n- **Link:** [\(.rule.id)](\(.html_url))\n"' >> security-report.md

    echo "" >> security-report.md
    echo "## 🟡 Warning Issues (${WARNINGS})" >> security-report.md
    echo "" >> security-report.md
    echo "$ALERTS" | jq -r '.[] | select(.rule.severity == "warning") | "### \(.rule.name)\n- **Rule:** `\(.rule.id)`\n- **File:** `\(.most_recent_instance.location.path)` (Line \(.most_recent_instance.location.start_line))\n- **Link:** [\(.rule.id)](\(.html_url))\n"' >> security-report.md

    echo "" >> security-report.md
    echo "## 🔵 Note Issues (${NOTES})" >> security-report.md
    echo "" >> security-report.md
    echo "$ALERTS" | jq -r '.[] | select(.rule.severity == "note") | "### \(.rule.name)\n- **Rule:** `\(.rule.id)`\n- **File:** `\(.most_recent_instance.location.path)` (Line \(.most_recent_instance.location.start_line))\n- **Link:** [\(.rule.id)](\(.html_url))\n"' >> security-report.md
fi

cat >> security-report.md << 'EOF'

---
*This report was automatically generated by GitHub Actions CodeQL scanning.*
EOF

echo "✓ Markdown report generated: security-report.md"

# Generate simple summary
cat > SECURITY_SUMMARY.txt << EOF
═══════════════════════════════════════════════════════════════════
  CODEQL SECURITY SCAN REPORT - $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)
═══════════════════════════════════════════════════════════════════

Repository: ${REPO}

SUMMARY:
  Total Alerts:     ${TOTAL}
  Critical Issues:  ${ERRORS}
  Warnings:         ${WARNINGS}
  Notes:            ${NOTES}

STATUS:
EOF

if [ "$TOTAL" -eq 0 ]; then
    echo "  ✅ PASS - No security issues detected" >> SECURITY_SUMMARY.txt
else
    echo "  ⚠️  REVIEW NEEDED - ${TOTAL} issue(s) found" >> SECURITY_SUMMARY.txt
fi

cat >> SECURITY_SUMMARY.txt << EOF

VIEW DETAILS:
  - Markdown Report: security-report.md
  - GitHub Page: https://github.com/${REPO}/security/code-scanning

═══════════════════════════════════════════════════════════════════
EOF

echo ""
echo "✓ Report generation completed successfully!"
echo "📊 Reports saved to:"
echo "   - security-report.md"
echo "   - SECURITY_SUMMARY.txt"
